export enum CustomException {
    // Required Errors
    FIRST_NAME_IS_REQUIRED = "FIRST_NAME_IS_REQUIRED",
    LAST_NAME_IS_REQUIRED = "LAST_NAME_IS_REQUIRED",
    USER_NAME_IS_REQUIRED = "USER_NAME_IS_REQUIRED",
    PASSWORD_IS_REQUIRED = "PASSWORD_IS_REQUIRED",
    CURRENCY_CODE_IS_REQUIRED = "CURRENCY_CODE_IS_REQUIRED",
    CURRENCY_SYMBOL_IS_REQUIRED = "CURRENCY_SYMBOL_IS_REQUIRED",

    // Exceptions
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    CURRENCY_CODE_ALREADY_EXIST = "CURRENCY_CODE_ALREADY_EXIST",
    UNAVAILABLE_USER_NAME = "UNAVAILABLE_USER_NAME",

    // Not Found Errors
    USER_NOT_FOUND = "USER_NOT_FOUND"
}